import Provider from "@/providers/ThemeProvider";
import "./globals.css";
import { AuthProvider } from "@/providers/AuthProvider";
import { QueryProvider } from "@/providers/QueryProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <QueryProvider>
          <AuthProvider>
            <Provider>
              <main>{children}</main>
            </Provider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
